#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
       dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
       main:
         pattern: ^/
         form_login:
              provider: fos_userbundle
              csrf_provider: form.csrf_provider
              always_use_default_target_path: true
              default_target_path: /
         logout: 
              target: /
         anonymous: true

    access_control:
        - { path: ^/login$,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestion/,  roles: ROLE_ADMIN }
        - { path: ^/,          roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
