services:
   login_listener:
      class: DevBieres\Task\WebHtmlBundle\Listener\LoginListener
      scope: request
      arguments: [@router, @security.context, @event_dispatcher, @session, @dvb.mng_user, @dvb.mng_tachesimple]
      tags:
          - { name: kernel.event_listener, event: security.interactive_login, method:onSecurityInteractiveLogin  }
